# System theme -> Neovim bridge, mirroring Omarchy's mechanism:
# Omarchy renders the active theme's palette into a `neovim.lua` (an
# aether.nvim v3 lazy spec with every palette color injected) that nvim loads
# as a theme plugin. Here the palette is resolved at build time from
# `config.themePalette` (single source of truth in ./themes/*.nix) and written
# by Home Manager to `~/.config/theme/neovim.lua`. The user's nvim repo then
# loads it via `lua/plugins/theme.lua` (see the `dofile` bridge there).
{config, ...}: let
  c = config.themePalette;
  q = color: ''"${color}"'';
in {
  xdg.configFile."theme/neovim.lua".text = ''
    -- Generated by the NixOS build from home/themes/${c.name}.nix.
    -- Any palette color injected here comes from that one file.
    return {
      {
        "bjarneo/aether.nvim",
        branch = "v3",
        name = "aether",
        priority = 1000,
        opts = {
          -- Ghostty/waybar own the 16-color terminal palette; aether must not
          -- stomp it (same fix as the miasma.nvim term_colors=false).
          terminal_colors = false,
          colors = {
            bg         = ${q c.bg},
            dark_bg    = ${q c.panel},
            darker_bg  = ${q c.normal.black},
            lighter_bg = ${q c.border},

            fg         = ${q c.fg},
            dark_fg    = ${q c.muted},
            light_fg   = ${q c.normal.white},
            bright_fg  = ${q c.bright.white},
            muted      = ${q c.muted},

            red        = ${q c.normal.red},
            yellow     = ${q c.normal.yellow},
            orange     = ${q c.bright.yellow},
            green      = ${q c.normal.green},
            cyan       = ${q c.normal.cyan},
            blue       = ${q c.normal.blue},
            purple     = ${q c.normal.magenta},
            brown      = ${q c.bright.red},

            bright_red    = ${q c.bright.red},
            bright_yellow = ${q c.bright.yellow},
            bright_green  = ${q c.bright.green},
            bright_cyan   = ${q c.bright.cyan},
            bright_blue   = ${q c.bright.blue},
            bright_purple = ${q c.bright.magenta},

            accent               = ${q c.accent},
            cursor               = ${q c.cursor},
            foreground           = ${q c.fg},
            background           = ${q c.bg},
            selection            = ${q c.border},
            selection_foreground = ${q c.selectionFg},
            selection_background = ${q c.accent},
          },
        },
        config = function(_, opts)
          require("aether").setup(opts)
          vim.cmd.colorscheme("aether")
        end,
      },
      {
        "AstroNvim/astroui",
        opts = {
          colorscheme = "aether",
        },
      },
    }
  '';
}
